[package]
name = "pine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["debug", "advanced"] }
aes = "0.8.4"
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
hex = "0.4.3"